#!/bin/sh
        SED="$(which sed)"
	echo 'modifing color in orange-scheme'
	( $SED 's/#6d140b/rgb(154,37,143)/g' -i /koolshare/webs/css/orange-scheme.css)
	echo 'set netgear theme as default'
uci batch <<-EOF
	set luci.themes.Netgear=/luci-static/netgear
	set luci.main.mediaurlbase=/luci-static/netgear
	commit luci
EOF
exit 0
